# IHACPA v2.0 Global Configuration

# Redis Configuration
redis:
  enabled: true
  url: "redis://localhost:6379"
  db: 0
  default_ttl: 3600  # 1 hour cache TTL

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/ihacpa.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Performance Settings (optimized for Azure OpenAI)
performance:
  parallel_scanning: true
  max_concurrent_scans: 2    # Reduced for Azure rate limits
  request_timeout: 45        # Increased for Azure API
  retry_attempts: 3
  retry_delay: 3.0           # Increased delay between retries

# AI/LLM Configuration
ai:
  enabled: true
  provider: "azure"  # azure, openai, anthropic
  model: "gpt-4.1"   # Azure deployment name
  temperature: 0.1
  max_tokens: 1000
  timeout: 45        # Increased for Azure OpenAI

# Security Settings
security:
  api_key_validation: true
  rate_limit_enforcement: true
  secure_headers: true

# Output Configuration
output:
  excel_format: true
  json_format: false
  detailed_reports: true
  color_coding: true
  
# Package Analysis
analysis:
  check_for_updates: true
  analyze_dependencies: true
  check_licenses: true
  detect_suspicious_patterns: true
  minimum_confidence: 0.5