# IHACPA v2.0 Configuration File
# AI-Enhanced Python Package Security Automation

app:
  name: "IHACPA v2.0 - AI-Enhanced Python Package Security Automation"
  version: "2.0.3"
  environment: "production"  # development, testing, production
  debug_mode: false

processing:
  max_concurrent_scans: 3
  request_timeout: 45
  retry_attempts: 3
  retry_delay: 2
  individual_package_processing: true

excel:
  backup_original: true
  preserve_formatting: true
  header_row: 3  # Row 3 contains the actual headers
  data_start_row: 4  # Data starts from row 4
  timestamp_backups: true
  sheet_name: "Sheet1"
  enhanced_columns_enabled: true  # Enable enhanced columns E, F, K, L, M, W by default
  enhanced_columns: ["E", "F", "H", "K", "L", "M", "P", "R", "T", "V", "W"]

output:
  generate_summary: true
  create_reports: true
  timestamp_files: true
  export_formats: ["xlsx", "json"]
  backup_directory: "data/backups"
  output_directory: "data/output"
  report_directory: "data/reports"

logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5
  log_directory: "logs"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_output: true

ai:
  enabled: true  # Enabled for AI demo
  provider: "azure"  # azure, openai, mock
  model: "gpt-4.1"
  temperature: 0.1
  timeout: 45
  max_tokens: 1000
  azure_api_version: "2025-01-01-preview"
  
  # AI Analysis Features
  correlation_analysis_enabled: true
  confidence_threshold: 0.7
  risk_assessment_enabled: true
  
  business_context:
    industry: "technology"
    asset_criticality: "high"
    data_sensitivity: "confidential"

# Note: API keys and endpoints should be set via environment variables:
# - AZURE_OPENAI_ENDPOINT
# - AZURE_OPENAI_KEY  
# - AZURE_OPENAI_MODEL
# - OPENAI_API_KEY (for OpenAI provider)